PackageIdentifier: IntegrationTests.InstallerValidation
PackageVersion: 1.0.41331.0
PackageName: Installer validation
Publisher: Microsoft Corporation
PackageUrl: https://code.visualstudio.com
License: Copyright (c) Microsoft Corporation
ShortDescription: Test for manifest installer
Moniker: winget
# PackageFamilyName: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
MinimumOSVersion: 10.0.16299.0
Installers:
- Architecture: x64
  InstallerUrl: https://stpkgmanvalwestustest.blob.core.windows.net/test-installers/TestInstaller.msixbundle
  InstallerType: msix
  InstallerSha256: e052ae8521b7e616342d5474ab36d848ffb1b6cac9364caa8dd8f2797fa2dd97
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0